create table if not exists "Users" (
    "Id" integer generated by default as identity primary key,
    "UserId" text not null,
    "Name" text not null,
    "Email" text not null,
    "Role" integer not null,
    "Major" integer null,
    "IsActive" boolean not null default true,
    "CreatedAt" timestamp with time zone not null default now()
);

create unique index if not exists "IX_Users_UserId"
    on "Users" ("UserId");

create table if not exists "Rooms" (
    "Id" integer generated by default as identity primary key,
    "Code" text not null,
    "Name" text not null,
    "Location" text not null,
    "Capacity" integer not null,
    "Type" integer not null,
    "Description" text not null,
    "IsAvailable" boolean not null default true,
    "CreatedAt" timestamp with time zone not null default now(),
    "UpdatedAt" timestamp with time zone not null default now()
);

create unique index if not exists "IX_Rooms_Code"
    on "Rooms" ("Code");

create table if not exists "Bookings" (
    "Id" integer generated by default as identity primary key,
    "RoomId" integer not null,
    "UserId" integer not null,
    "BookingDate" timestamp with time zone not null,
    "StartTime" time without time zone not null,
    "EndTime" time without time zone not null,
    "Status" integer not null default 0,
    "Notes" text null,
    "RecurrencePattern" integer not null default 0,
    "RecurrenceEndDate" timestamp with time zone null,
    "ConfirmationNumber" text null,
    "CreatedAt" timestamp with time zone not null default now(),
    "UpdatedAt" timestamp with time zone not null default now(),
    constraint "FK_Bookings_Rooms_RoomId"
        foreign key ("RoomId") references "Rooms" ("Id") on delete cascade,
    constraint "FK_Bookings_Users_UserId"
        foreign key ("UserId") references "Users" ("Id") on delete cascade
);

create index if not exists "IX_Bookings_RoomId_BookingDate"
    on "Bookings" ("RoomId", "BookingDate");

create table if not exists "RoomMajorRestrictions" (
    "Id" integer generated by default as identity primary key,
    "RoomId" integer not null,
    "Major" integer not null,
    "IsActive" boolean not null default true,
    "CreatedAt" timestamp with time zone not null default now(),
    constraint "FK_RoomMajorRestrictions_Rooms_RoomId"
        foreign key ("RoomId") references "Rooms" ("Id") on delete cascade
);

create unique index if not exists "IX_RoomMajorRestrictions_RoomId_Major"
    on "RoomMajorRestrictions" ("RoomId", "Major");